name: Bug Report
description: Report an issue with the bot
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a bug report, please:
        - Verify the issue persists on the latest version
        - Search existing issues
        - Check the documentation
        - Test in a clean environment

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: v16.9.0
    validations:
      required: true

  - type: input
    id: discord-js-version
    attributes:
      label: Discord.js Version
      description: What version of Discord.js are you using?
      placeholder: v14.14.1
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: What happened and what did you expect to happen?
      placeholder: Describe the issue and expected behavior
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this issue?
      placeholder: |
        1. Create a command...
        2. Execute with...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include any relevant error logs or output
      render: shell

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please verify that you have completed these steps
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched for existing issues
          required: true
        - label: I am using the latest version
          required: true
        - label: I have tested in a clean environment
          required: true

