blank_issues_enabled: false
contact_links:
  - name: Discord.js Guide
    url: https://discordjs.guide/
    about: Official Discord.js documentation and guides
  - name: Discord.js Documentation
    url: https://discord.js.org/
    about: Complete Discord.js API reference

