name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: # Set default permissions to none
  contents: read

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only needs read access to check out code

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: |
          if [ -f "package.json" ] && grep -q "\"test\":" "package.json"; then
            npm test
          else
            echo "No tests found. You should feel bad."
            exit 0
          fi

  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only needs read access to check out code
      pull-requests: write # Needs write access to add labels to PRs
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

