name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check if you can write JavaScript
        run: npm run lint

      - name: Run tests (if they exist)
        run: |
          if [ -f "package.json" ] && grep -q "\"test\":" "package.json"; then
            npm test
          else
            echo "No tests found. You should feel bad."
            exit 0
          fi

  # Label PRs because organization
  labeler:
    name: Label PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml

